resources:
- ../../base



configMapGenerator:
- name: mykustom-map
  behavior: replace
  env: .env_prod
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: user-pass
  envs:
  - .secret_prod


patches:
  - target:
       kind: Deployment
       name: react-app-back
    patch: |-
       - op: replace
         path: /spec/replicas
         value: 5
       - op: add
         path: /spec/template/metadata/labels/app1
         value: test





images:
- name: houwayda/ecom-front
  newName: docker.io/houwayda/ecom_front_prod
  newTag: a2482e1fd03a8877e02ef98acdab5e7525d619b4
  
- name: houwayda/ecom-back
  newName: docker.io/houwayda/ecom_back_prod
  newTag: ce8e7d01ec40985846962262dd7ad5a2b8830552
