resources:
- ../../base



configMapGenerator:
- name: mykustom-map
  env: .env
  options:
    disableNameSuffixHash: true




patches:
  - target:
       kind: Deployment
       name: react-app-back
    patch: |-
       - op: replace
         path: /spec/replicas
         value: 5
       - op: add
         path: /spec/template/metadata/labels/app1
         value: test


configMapGenerator:
- name: mykustom-map
  behavior: replace
  env: .env
  options:
    disableNameSuffixHash: true


images:
- name: houwayda/ecom-front
  newName: docker.io/houwayda/ecom_front_prod
  newTag: a2482e1fd03a8877e02ef98acdab5e7525d619b4
  
- name: houwayda/ecom-back
  newName: docker.io/houwayda/ecom_back_prod
  newTag: eec8528e6b0ca2280ce9d17f6c35060568641ba7
