resources:
- ../../base



configMapGenerator:
- name: mykustom-map
  behavior: replace
  env: .env_prod
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: myapp-secrets
  behavior: replace
  envs:
  - .secrets_prod
  options:
    disableNameSuffixHash: true

patches:
  - target:
       kind: Deployment
       name: react-app-back
    patch: |-
       - op: replace
         path: /spec/replicas
         value: 1
       - op: add
         path: /spec/template/metadata/labels/app1
         value: test





images:
- name: houwayda/ecom-front
  newName: docker.io/houwayda/ecom_front_prod
  newTag: f26f09851188703e8df34900c498264f2ae8cfc6
  
- name: houwayda/ecom-back
  newName: docker.io/houwayda/ecom_back_prod
  newTag: f8c24bccb680a46229df8d0516335dc4cc9b2d31
