resources:
- ../../base



configMapGenerator:
- name: mykustom-map
  behavior: replace
  env: .env_prod
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: myapp-secrets
  behavior: replace
  envs:
  - .secrets_prod
  options:
    disableNameSuffixHash: true

patches:
  - target:
       kind: Deployment
       name: react-app-back
    patch: |-
       - op: replace
         path: /spec/replicas
         value: 1
       - op: add
         path: /spec/template/metadata/labels/app1
         value: test





images:
- name: houwayda/ecom-front
  newName: docker.io/houwayda/ecom_front_prod
  newTag: 7810ade2c52e24dfc5ec81838433525326d4cc1c
  
- name: houwayda/ecom-back
  newName: docker.io/houwayda/ecom_back_prod
  newTag: 8512aa71b557175539ffff184f76d82467d2e1e5
