bases:
- ../../base

patches:
  - target:
       kind: Deployment
       name: react-app-back
    patch: |-
       - op: replace
         path: /spec/replicas
         value: 5
       - op: add
         path: /spec/template/metadata/labels/app1
         value: test

commonLabels:
 env: production

images:
- name: houwayda/ecom-front
  newName: docker.io/houwayda/ecom_front_prod
  newTag: c7135f0492787716eba6ddae0678042b17e82306
  
- name: houwayda/ecom-back
  newName: docker.io/houwayda/ecom_prod
  newTag: cb738b39e8c290bcef0f13c5602d750e436e8ad9
