
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app-back
  template:
    metadata:
      labels:
        app: react-app-back
    spec:
      containers:
        - name: react-app-back
          image: houwayda/ecom-backt:29fcd51ea82875d0a6e1c99177b1ace84f881d90
          imagePullPolicy: Always
          ports:
            - containerPort: 80

  revisionHistoryLimit: 1
