resources:
- deployment_front.yaml
- service_front.yaml
- deployment_back.yaml
- service_back.yaml
- mongodb_deploy.yaml
- mongodb_service.yaml



configMapGenerator:
- name: mykustom-map
  env: .env
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: user-pass
  envs:
  - .secrets
