resources:
- deployment_front.yaml
- service_front.yaml
- deployment_back.yaml
- service_back.yaml
- mongodb_deploy.yaml
- mongodb_service.yaml



configMapGenerator:
  - name: app-config
    files:
      - app.properties

secretGenerator:
  - name: app-secrets
    literals:
      - secret-key=SECRET_VALUE_HERE
