resources:
- deployment_front.yaml
- service_front.yaml
- deployment_back.yaml
- service_back.yaml
- mongodb_deploy.yaml
- mongodb_service.yaml



images:
- name: houwayda/ecom-front
  newName: docker.io/houwayda/ecom-front
  newTag: 6d8c9316f0be95232b3855b2561429953aeb9be9
