bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: houwayda/ecom-front
  newName: docker.io/houwayda/ecom-front
  newTag: f9d20931773d4b0ed4fbb14f7414ff428e69f32c
  
- name: houwayda/ecom-back
  newName: docker.io/houwayda/ecom-back
  newTag: f462cab645b9e6feb1fc23a926444ccdfeacebb3
